Maj m1
MTES-MCT/parcours_r_socle_introduction pull request #12
Opened 2021-09-30 12:27 UTC by MurielleL

Modif pour maj_m1:

- chemin pour se caler à savoirfR
- renommage du dossier data -> extdata (comme dans savoirfR)
- carte des membres du G2R (non définitif en attente de la liste par OChantrel)

render_book(): OK

2021-09-30 12:49 UTC, NicolasTrtrtt requested changes
3 corrections de coquilles (02-l23, 04_l25 et 55)
2 propositions d'ajouts (03-l69 et fin)

2021-09-30 15:15 UTC, jdlom reviewed
Ras pour ma part.
Le problème avec le chunk m'interroge

2021-09-30 15:15 UTC, jdlom commented on 07-stats.Rmd
> +(prop.table(t,margin=2) * 100) %>%
Étonnant que le chunk ne passe pas alors qu'il est passé sur la version en ligne. Tu fais le rendu du chapitre ou du Book en entier ? Je vais regarder.

2021-10-05 14:24 UTC, jdlom approved these changes

2021-10-05 14:26 UTC, jdlom approved these changes

2021-10-05 14:27 UTC, jdlom approved these changes

2021-10-05 14:29 UTC, merged